AWSTemplateFormatVersion: "2010-09-09"

Description: Postgres For LenSentApp

Parameters:
  DBName:
    Type: String
    Default: "LENSENT"
  DBMasterUserName:
    Type: String
    Default: "postgres"
    NoEcho: true
  DBMasterUserPassword: 
    Default: "postgres"
    NoEcho: true
    Type: String

Resources:
  ApplicationDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 13.3
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBMasterUserPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref ApplicationDatabaseSecurityGroup
      DBSubnetGroupName: !Ref ApplicationDatabaseSubnetGroup
      MultiAZ: "false"
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db
  ApplicationDatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Application Database Subnet Group
      SubnetIds: 
        - !ImportValue RDSSubnet1Name
        - !ImportValue RDSSubnet2Name
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-subnet-group
  ApplicationDatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName} Application Database Security Group
      VpcId: !ImportValue LenSentVPCName
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: 10.0.0.0/24
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-sg

Outputs:
  ApplicationDatabase:
    Value: !Ref ApplicationDatabase
    Export:
      Name: ApplicationDatabaseName
  DBMasterUsername:
    Value: !Ref DBMasterUserName
    Export: DBMasterUsername
  DBMasterUserPassword:
    Value: !Ref DBMasterUserPassword
    Export: DBMasterUserPassword
  DBName:
    Value: !Ref DBName
    Export: DBName
  DBEndpoint:
    Value: !GetAtt: Endpoint.Address
    Export: DBEndpoint
  DBPort:
    Value: !GetAtt: Endpoint.Port
    Export: DBPort
  ApplicationDatabaseSubnetGroup:
    Value: !Ref ApplicationDatabaseSubnetGroup
    Export:
      Name: ApplicationDatabaseSubnetGroupName
  ApplicationDatabaseSecurityGroup:
    Value: !Ref ApplicationDatabaseSecurityGroup
    Export:
      Name: ApplicationDatabaseSecurityGroupName