AWSTemplateFormatVersion: 2010-09-09
Description: S3-bucket For LenSentApp

Mappings:
  S3Config:
    ap-northeast-1:
      BucketPrincipal: "582318560864"

Resources:
  ELBLogBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Join [ "-", [ elblog , Ref: "AWS::AccountId" ] ]
  BucketPolicyELBLogBucket:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: "ELBLogBucket"
      PolicyDocument:
        Id: "Allow-Put-ELB-logs"
        Version: "2012-10-17"
        Statement:
          -
            Sid: "Stmt1429136633762"
            Action:
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: "ELBLogBucket"
                  - "/AWSLogs/"
                  -
                    Ref: AWS::AccountId
                  - "/*"
            Principal:
              AWS: !FindInMap [ S3Config, Ref: "AWS::Region", BucketPrincipal ]

Outputs:
  ELBLogBucket:
    Value: !Ref ELBLogBucket
    Export:
      Name: ELBLogBucketName