AWSTemplateFormatVersion: 2010-09-09
Description: Security Group For LenSentApp

Resources: 
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: LenSentALBSecurityGroup
      GroupName: ALB-SG
      VpcId: !ImportValue LenSentVPCName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: LenSentECSSecurityGroup
      GroupName: ECS-SG
      VpcId: !ImportValue LenSentVPCName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

Outputs:
  ALBSecurityGroup:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: ALBSecurityGroupName
  ECSSecurityGroup:
    Value: !Ref ECSSecurityGroup
    Export:
      Name: ECSSecurityGroupName