# テンプレート形式のバージョン
AWSTemplateFormatVersion: 2010-09-09

# テンプレートに関する記述
Description: VPC For LenSentApp

# 構築するリソースの記述
Resources: 
  # VPC
  LenSentVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/21
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: LenSentVPCfromCF
  # Publicサブネット
  ECSSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref LenSentVPC 
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: ECSSubnet1fromcf
  ECSSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref LenSentVPC 
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: ECSSubnet2fromcf
  RDSSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !Ref LenSentVPC 
      CidrBlock: 10.1.0.0/24
      Tags:
        - Key: Name
          Value: RDSSubnet1fromcf
  RDSSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !Ref LenSentVPC 
      CidrBlock: 10.2.0.0/24
      Tags:
        - Key: Name
          Value: RDSSubnet2fromcf
  # Publicサブネットのルートテーブル
  ECSSubnet1RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LenSentVPC
      Tags:
        - Key: Name
          Value: ECSSubnet1RTfromcf
  ECSSubnet2RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LenSentVPC
      Tags:
        - Key: Name
          Value: ECSSubnet2RTfromcf
  RDSSubnet1RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LenSentVPC
      Tags:
        - Key: Name
          Value: RDSSubnet1RTfromcf
  RDSSubnet2RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LenSentVPC
      Tags:
        - Key: Name
          Value: RDSSubnet2RTfromcf
  # インターネットゲートウェイのルートテーブル
  ECSSubnet1ToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ECSSubnet1RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
  AssoECSSubnet1RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ECSSubnet1
      RouteTableId: !Ref ECSSubnet1RT
  ECSSubnet2ToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ECSSubnet2RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
  AssoECSSubnet2RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ECSSubnet2
      RouteTableId: !Ref ECSSubnet2RT
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref LenSentVPC
      InternetGatewayId: !Ref IGW
  # インターネットゲートウェイ
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGWfromcf

# 出力変数
Outputs:
  LenSentVPC:
      Value: !Ref LenSentVPC 
      Export:
        Name: LenSentVPCName
  ECSSubnet1:
      Value: !Ref ECSSubnet1
      Export:
        Name: ECSSubnet1Name
  ECSSubnet2:
      Value: !Ref ECSSubnet2
      Export:
        Name: ECSSubnet2Name
  RDSSubnet1:
      Value: !Ref RDSSubnet1
      Export:
        Name: RDSSubnet1Name
  RDSSubnet2:
      Value: !Ref RDSSubnet2
      Export:
        Name: RDSSubnet2Name
  IGW:
      Value: !Ref IGW
      Export:
        Name: IGWName 